# 🌳 **Alphabet_NLP_Dataset**

## 🟢 **Imports**

In [12]:
import json
import psutil
import pandas as pd
import os
from pprint import pprint

from tokenizers import Tokenizer, models, trainers, pre_tokenizers, decoders, processors

## 🟢 **`JSON` to `Parquet`**

### 🌿 **Alphabet_NLP_Dataset**

In [3]:
# Read JSON file
json_path = "raw/dataset/Alphabet_NLP_Dataset.json"

with open(json_path, "r", encoding="utf-8") as f:
    dataset = json.load(f)

normalized_data = []
for item in dataset:
    new_item = item.copy()
    normalized_data.append(new_item)

df_json = pd.DataFrame(normalized_data)

# Save to Parquet format
parquet_path = "parquet/Alphabet_NLP_Dataset.parquet"
df_json.to_parquet(parquet_path, index=False)

# Load the Parquet data
df_loaded = pd.read_parquet(parquet_path)

# Display as a table
df_loaded

,input_text,target_text,source,editor,id
0,سلام,سلام! چطور می‌تونم کمکتون کنم؟ 😊,ARK,Ghasem Arianpour,1
1,مدل زبانی آرک,من یک **مدل زبانی** هستم با نام **آرک (ARK)** ...,ARK,Ghasem Arianpour,2
2,آیا بسم اللّه جزء سوره است؟,در میان دانشمندان و علماء شیعه، اختلافى در این...,quran.makarem.ir,Ghasem Arianpour,3
3,جامع‌ترین نام خداوند,در جمله‌ی «بسم اللّه»، نخست با کلمه‌ی «اسم» رو...,quran.makarem.ir,Ghasem Arianpour,4
4,رحمت عام و رحمت خاص خدا,مشهور در میان گروهى از مفسران این است که: صفت ...,quran.makarem.ir,Ghasem Arianpour,5
...,...,...,...,...,...
157,سکونت‌پذیری یک سیاره در منظومه تراپیست 1,### واپسین امیدهای اخترشناسان؛ یکی از سیاره‌ها...,zoomit.ir,Ghasem Arianpour,158
158,پیش‌بینی نتیجه آزمایش‌های همجوشی هسته‌ای با هو...,### پیشرفت بزرگ در همجوشی هسته‌ای: هوش مصنوعی ...,zoomit.ir,Ghasem Arianpour,159
159,کتابخانه DNA جانوران در پشه‌ها,### پارک ژوراسیک درست می‌گفت: پشه‌ها واقعاً کت...,zoomit.ir,Ghasem Arianpour,160
160,قدمت هرم بزرگ جیزه,### ادعای جنجالی یک پژوهشگر: قدمت هرم بزرگ جیز...,zoomit.ir,Ghasem Arianpour,161
161,خواص دعای شرف‌الشمس,نگین یا انگشتر یا آویز شرف‌الشمس برای ایمنی در...,Ghasem Arianpour's Notebook,Ghasem Arianpour,162

In [25]:
dataset = pd.read_parquet("parquet/Alphabet_NLP_Dataset.parquet")

dataset.head()

num_samples = len(dataset)

total_tokens = 0
text_columns = ["input_text", "target_text"]

for col in text_columns:
    if col in dataset.columns:
        total_tokens += dataset[col].astype(str).apply(lambda x: len(x.split())).sum()

print("🔢 Number of samples:", num_samples)
print("📝 Total number of tokens:", total_tokens)

🔢 Number of samples: 162
📝 Total number of tokens: 62791

### 🌿 **Alphabet_Codex_Dataset**

In [3]:
extracted_folder = "raw/dataset/Alphabet_Codex_Dataset/"

# Filter for JSON files directly in the 'extracted_folder'
json_files = [f for f in os.listdir(extracted_folder) if f.endswith('.json')]

# Debugging: Print found JSON files
if not json_files:
    print("No JSON files found in the specified JSON source folder (extracted_folder).")
else:
    print(f"Found {len(json_files)} JSON files: {json_files}")

all_data = []

for file_name in json_files:
    json_path = os.path.join(extracted_folder, file_name)
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
        if isinstance(data, list):
            all_data.extend(data)
        elif isinstance(data, dict):
            all_data.append(data)

df_json = pd.DataFrame(all_data)

parquet_path = "parquet/Alphabet_Codex_Dataset.parquet"
os.makedirs("parquet", exist_ok=True)
df_json.to_parquet(parquet_path, index=False)

df_loaded = pd.read_parquet(parquet_path)

df_loaded.head()

Found 23 JSON files: ['Android.json', 'Assembly.json', 'C#.json', 'C++.json', 'C.json', 'CMD.json', 'CSS.json', 'Django.json', 'Flask.json', 'HTML.json', 'Java.json', 'JavaScript.json', 'jQuery.json', 'Kotlin.json', 'Laravel.json', 'Node.js.json', 'PHP.json', 'Python.json', 'PyTorch.json', 'SmallBasic.json', 'SQL.Server.json', 'TensorFlow.&.Keras.json', 'TypeScript.json']

,input_text,target_text,source,editor,id
0,اندروید (Android) چیست و چرا برنامه‌نویسی اندر...,اندروید (Android) یک سیستم‌عامل مبتنی‌بر لینوک...,ChatGPT,Ghasem Arianpour,1
1,آشنایی با اکوسیستم اندروید و نسخه‌های آن,اکوسیستم اندروید، مجموعه‌ای از سیستم‌عامل، ابز...,ChatGPT,Ghasem Arianpour,2
2,اندروید (Android),اندروید (Android)، سیستم‌عامل (Operating Syste...,ChatGPT,Ghasem Arianpour,3
3,برنامه‌نویسی اندروید,توسعه‌ی اپلیکیشن درواقع فرایند گام‌به‌گامی است...,ChatGPT,Ghasem Arianpour,4
4,فرگمنت در برنامه‌نویسی اندروید,در توسعه‌ی نرم‌افزارهای مدرن اندروید، استفاده ...,blog.faradars.org,Ghasem Arianpour,5

In [4]:
dataset = pd.read_parquet("parquet/Alphabet_Codex_Dataset.parquet")

dataset.head()

num_samples = len(dataset)

total_tokens = 0
text_columns = ["input_text", "target_text"]

for col in text_columns:
    if col in dataset.columns:
        total_tokens += dataset[col].astype(str).apply(lambda x: len(x.split())).sum()

print("🔢 Number of samples:", num_samples)
print("📝 Total number of tokens:", total_tokens)

🔢 Number of samples: 198
📝 Total number of tokens: 47558

### 🌿 **Alphabet_Science_Dataset**

In [6]:
extracted_folder = "raw/dataset/Alphabet_Science_Dataset/"

# Filter for JSON files directly in the 'extracted_folder'
json_files = [f for f in os.listdir(extracted_folder) if f.endswith('.json')]

# Debugging: Print found JSON files
if not json_files:
    print("No JSON files found in the specified JSON source folder (extracted_folder).")
else:
    print(f"Found {len(json_files)} JSON files: {json_files}")

all_data = []

for file_name in json_files:
    json_path = os.path.join(extracted_folder, file_name)
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
        if isinstance(data, list):
            all_data.extend(data)
        elif isinstance(data, dict):
            all_data.append(data)

df_json = pd.DataFrame(all_data)

parquet_path = "parquet/Alphabet_Science_Dataset.parquet"
df_json.to_parquet(parquet_path, index=False)

df_loaded = pd.read_parquet(parquet_path)

df_loaded.head()

Found 22 JSON files: ['Aerospace.json', 'Agriculture.json', 'AI.json', 'Astrophysics.json', 'Botany.json', 'Chemistry.json', 'Economic.json', 'Electricity.json', 'Genetic.json', 'Geology.json', 'Mathematics.json', 'Mechanic.json', 'Medicine.json', 'Midwifery.json', 'Nanotechnology.json', 'Nerves.json', 'Nuclear.Physics.json', 'Pharmacy.json', 'Physics.json', 'Psychology.json', 'Quantum.Physics.json', 'Universe.json']

,input_text,target_text,source,editor,id
0,مهندسی هوافضا چیست و چه کاربردهایی دارد؟,مهندسی هوافضا شاخه‌ای از مهندسی است که به طراح...,ChatGPT,Ghasem Arianpour,1
1,تاریخچه مهندسی هوافضا,مهندسی هوافضا با ریشه در قرن نوزدهم و اوایل قر...,ChatGPT,Ghasem Arianpour,2
2,پهپاد,گرچه امروزه کلمه‌ی پهپاد به‌صورت گسترده استفاد...,blog.faradars.org,Ghasem Arianpour,3
3,انواع پهپاد,پهپادها ابتدا برای اهداف نظامی و صنایع هوافضا ...,blog.faradars.org,Ghasem Arianpour,4
4,پهپادهای مبتنی‌بر ملخ,پهپادهای مبتنی‌بر ملخ، یکی از رایج‌ترین و پرکا...,blog.faradars.org,Ghasem Arianpour,5

In [7]:
dataset = pd.read_parquet("parquet/Alphabet_Science_Dataset.parquet")

dataset.head()

num_samples = len(dataset)

total_tokens = 0
text_columns = ["input_text", "target_text"]

for col in text_columns:
    if col in dataset.columns:
        total_tokens += dataset[col].astype(str).apply(lambda x: len(x.split())).sum()

print("🔢 Number of samples:", num_samples)
print("📝 Total number of tokens:", total_tokens)

🔢 Number of samples: 384
📝 Total number of tokens: 60185

### 🌿 **Alphabet_Technology_Dataset**

In [4]:
extracted_folder = "raw/dataset/Alphabet_Technology_Dataset/"

# Filter for JSON files directly in the 'extracted_folder'
json_files = [f for f in os.listdir(extracted_folder) if f.endswith('.json')]

# Debugging: Print found JSON files
if not json_files:
    print("No JSON files found in the specified JSON source folder (extracted_folder).")
else:
    print(f"Found {len(json_files)} JSON files: {json_files}")

all_data = []

for file_name in json_files:
    json_path = os.path.join(extracted_folder, file_name)
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
        if isinstance(data, list):
            all_data.extend(data)
        elif isinstance(data, dict):
            all_data.append(data)

df_json = pd.DataFrame(all_data)

parquet_path = "parquet/Alphabet_Technology_Dataset.parquet"
df_json.to_parquet(parquet_path, index=False)

df_loaded = pd.read_parquet(parquet_path)

df_loaded.head()

Found 11 JSON files: ['AVR.Microcontroller.json', 'BIOS.json', 'CCNA.json', 'CMS.json', 'Computer.json', 'Kali.Linux.json', 'Mobile.json', 'Office.json', 'Photoshop.json', 'Robotics.json', 'Self-control.json']

,input_text,target_text,source,editor,id
0,میکروکنترلر و تفاوت آن با میکروپروسسور,میکروکنترلر یک مدار مجتمع است که شامل پردازنده...,ChatGPT,Ghasem Arianpour,1
1,معرفی خانواده AVR و تاریخچه آن,خانواده‌ی AVR مجموعه‌ای از میکروکنترلرهای ۸ بی...,ChatGPT,Ghasem Arianpour,2
2,میکروکنترلر,میکروکنترلرها نوعی چیپ الکترونیکی قابل برنامه‌...,iairan.ir/neuromorphic,Ghasem Arianpour,3
3,معماری میکروکنترلر AVR,در میکروکنترلر AVR از دو نوع معماری بهره برده ...,iairan.ir/neuromorphic,Ghasem Arianpour,4
4,ساختار میکروکنترلر AVR,برخی از اجزای تشکیل‌دهنده‌ی میکروکنترلر AVR به...,iairan.ir/neuromorphic,Ghasem Arianpour,5

In [5]:
dataset = pd.read_parquet("parquet/Alphabet_Technology_Dataset.parquet")

dataset.head()

num_samples = len(dataset)

total_tokens = 0
text_columns = ["input_text", "target_text"]

for col in text_columns:
    if col in dataset.columns:
        total_tokens += dataset[col].astype(str).apply(lambda x: len(x.split())).sum()

print("🔢 Number of samples:", num_samples)
print("📝 Total number of tokens:", total_tokens)

🔢 Number of samples: 109
📝 Total number of tokens: 26307

### 🌿 **Alphabet_Quran_Dataset**

In [10]:
json_path = "raw/dataset/Quran.json"

if not os.path.exists(json_path):
    print(f"Error: JSON file not found at {json_path}")
else:
    print(f"JSON file found at {json_path}")

with open(json_path, "r", encoding="utf-8") as f:
    data = json.load(f)

if isinstance(data, dict):
    all_data = [data]
elif isinstance(data, list):
    all_data = data
else:
    raise ValueError("فرمت فایل JSON ناشناخته است!")

df_json = pd.DataFrame(all_data)

parquet_path = "parquet/Alphabet_Quran_Dataset.parquet"
df_json.to_parquet(parquet_path, index=False)
print(f"Dataset saved to {parquet_path}")

df_loaded = pd.read_parquet(parquet_path)
df_loaded.head()

JSON file found at raw/dataset/Quran.json
Dataset saved to parquet/Alphabet_Quran_Dataset.parquet

,input_text,target_text,source,editor,id
0,سوره فاتحه - آیه 1,### سوره‌ی فاتحه - آیه‌ی 1\n**بِسْمِ اللَّهِ ا...,wiki.ahlolbait.com,Ghasem Arianpour,1
1,سوره فاتحه - آیه 2,### سوره‌ی فاتحه - آیه‌ی 2\n**الْحَمْدُ لِلَّه...,wiki.ahlolbait.com,Ghasem Arianpour,2
2,سوره فاتحه - آیه 3,### سوره‌ی فاتحه - آیه‌ی 3\n**الرَّحْمَٰنِ الر...,wiki.ahlolbait.com,Ghasem Arianpour,3
3,سوره فاتحه - آیه 4,### سوره‌ی فاتحه - آیه‌ی 4\n**مَالِكِ يَوْمِ ا...,wiki.ahlolbait.com,Ghasem Arianpour,4
4,سوره فاتحه - آیه 5,### سوره‌ی فاتحه - آیه‌ی 5\n**إِيَّاكَ نَعْبُد...,wiki.ahlolbait.com,Ghasem Arianpour,5

In [11]:
dataset = pd.read_parquet("parquet/Alphabet_Quran_Dataset.parquet")

dataset.head()

num_samples = len(dataset)

total_tokens = 0
text_columns = ["input_text", "target_text"]

for col in text_columns:
    if col in dataset.columns:
        total_tokens += dataset[col].astype(str).apply(lambda x: len(x.split())).sum()

print("🔢 Number of samples:", num_samples)
print("📝 Total number of tokens:", total_tokens)

🔢 Number of samples: 126
📝 Total number of tokens: 27671

### 🌿 **Alphabet_Jurisprudence_Dataset**

In [12]:
json_path = "raw/dataset/Jurisprudence.json"

if not os.path.exists(json_path):
    print(f"Error: JSON file not found at {json_path}")
else:
    print(f"JSON file found at {json_path}")

with open(json_path, "r", encoding="utf-8") as f:
    data = json.load(f)

if isinstance(data, dict):
    all_data = [data]
elif isinstance(data, list):
    all_data = data
else:
    raise ValueError("فرمت فایل JSON ناشناخته است!")

df_json = pd.DataFrame(all_data)

parquet_path = "parquet/Alphabet_Jurisprudence_Dataset.parquet"
df_json.to_parquet(parquet_path, index=False)
print(f"Dataset saved to {parquet_path}")

df_loaded = pd.read_parquet(parquet_path)
df_loaded.head()

JSON file found at raw/dataset/Jurisprudence.json
Dataset saved to parquet/Alphabet_Jurisprudence_Dataset.parquet

,input_text,target_text,source,editor,id
0,وضو، غسل و تیمم: تعریف و شرایط هر یک,وضو عملی است که با شستن یا مسح اعضای خاص همراه...,Jurisprudence Lesson Notes - Mohammad Hossein ...,Ghasem Arianpour,1
1,تفاوت بین مکلَّف و مکلِّف,### 1️⃣ مکلَّف (فتحه روی لام مشدّد)\nکسی که با...,ChatGPT,Ghasem Arianpour,2
2,تفاوت فقیه با مرجع تقلید,### تفاوت فقیه با مرجع تقلید:\nفقیه مورد رجوع ...,Jurisprudence Lesson Notes - Mohammad Hossein ...,Ghasem Arianpour,3
3,شرایط مرجع تقلید,### شرایط مرجع تقلید:\n1. اجتهاد\n2. عقل و بلو...,Jurisprudence Lesson Notes - Mohammad Hossein ...,Ghasem Arianpour,4
4,مفهوم عدالت در مرجع تقلید,عدالت در مرجع تقلید، حالتی نفسانی است که انسان...,Jurisprudence Lesson Notes - Mohammad Hossein ...,Ghasem Arianpour,5

In [13]:
dataset = pd.read_parquet("parquet/Alphabet_Jurisprudence_Dataset.parquet")

dataset.head()

num_samples = len(dataset)

total_tokens = 0
text_columns = ["input_text", "target_text"]

for col in text_columns:
    if col in dataset.columns:
        total_tokens += dataset[col].astype(str).apply(lambda x: len(x.split())).sum()

print("🔢 Number of samples:", num_samples)
print("📝 Total number of tokens:", total_tokens)

🔢 Number of samples: 30
📝 Total number of tokens: 1350

### 🌿 **Alphabet_Philologia_Dataset**

In [14]:
extracted_folder = "raw/dataset/Alphabet_Philologia_Dataset/"

# Filter for JSON files directly in the 'extracted_folder'
json_files = [f for f in os.listdir(extracted_folder) if f.endswith('.json')]

# Debugging: Print found JSON files
if not json_files:
    print("No JSON files found in the specified JSON source folder (extracted_folder).")
else:
    print(f"Found {len(json_files)} JSON files: {json_files}")

all_data = []

for file_name in json_files:
    json_path = os.path.join(extracted_folder, file_name)
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
        if isinstance(data, list):
            all_data.extend(data)
        elif isinstance(data, dict):
            all_data.append(data)

df_json = pd.DataFrame(all_data)

parquet_path = "parquet/Alphabet_Philologia_Dataset.parquet"
df_json.to_parquet(parquet_path, index=False)

df_loaded = pd.read_parquet(parquet_path)

df_loaded.head()

Found 3 JSON files: ['Cuneiform.json', 'English.json', 'Hieroglyphic.json']

,input_text,target_text,source,editor,id
0,خط میخی,خط میخی یکی از قدیمی‌ترین نظام‌های نوشتاری جها...,ChatGPT,Ghasem Arianpour,1
1,تاریخچه پیدایش خط میخی,خط میخی، نخستین‌بار در حدود ۳۲۰۰ سال پیش از می...,ChatGPT,Ghasem Arianpour,2
2,تمدن‌های استفاده کننده از خط میخی,تمدن‌های زیادی در خاور نزدیک باستان از خط میخی...,ChatGPT,Ghasem Arianpour,3
3,زمان‌های انگلیسی,سه نوع زمان در زبان انگلیسی وجود دارد که وقوع ...,blog.faradars.org,Ghasem Arianpour,1
4,زمان حال ساده انگلیسی,از زمان «حال ساده» (Simple Present) برای بیان ...,blog.faradars.org,Ghasem Arianpour,2

In [15]:
dataset = pd.read_parquet("parquet/Alphabet_Philologia_Dataset.parquet")

dataset.head()

num_samples = len(dataset)

total_tokens = 0
text_columns = ["input_text", "target_text"]

for col in text_columns:
    if col in dataset.columns:
        total_tokens += dataset[col].astype(str).apply(lambda x: len(x.split())).sum()

print("🔢 Number of samples:", num_samples)
print("📝 Total number of tokens:", total_tokens)

🔢 Number of samples: 23
📝 Total number of tokens: 4075

## 🟢 **EDA**

### 🔴 Exploring the Dataset

In [7]:
base_path = "parquet/"

files = [
    "Alphabet_NLP_Dataset.parquet",
    "Alphabet_Codex_Dataset.parquet",
    "Alphabet_Jurisprudence_Dataset.parquet",
    "Alphabet_Quran_Dataset.parquet",
    "Alphabet_Science_Dataset.parquet",
    "Alphabet_Technology_Dataset.parquet",
    "Alphabet_Philologia_Dataset.parquet"
]

datasets = [pd.read_parquet(base_path + file) for file in files]

dataset = pd.concat(datasets, ignore_index=True)

dataset.head()
print("🔢 Number of samples:", len(dataset))

🔢 Number of samples: 1032

In [8]:
sample = dataset.sample(n=1)
pprint(sample.to_dict(orient="records")[0])

{'editor': 'Ghasem Arianpour',
 'id': 7,
 'input_text': 'توضیحات در اکسل',
 'source': 'blog.faradars.org',
 'target_text': 'به\u200cطور خلاصه، چهار مورد استفاده برای توضیحات (Comments) '
                'در اِکسل وجود دارد:\n'
                '- تعیین یادآوری برای وظایفی که روی یک فایل باید انجام شوند.\n'
                '- افزودن یادداشت برای خود و یا افراد دیگر\n'
                '- توضیح فرمول در یک سلول\n'
                '- توضیح شیوه\u200cی استفاده از بخش\u200cهای مختلف فایل.\n'
                '\n'
                '### افزودن توضیح به یک سلول\n'
                'برای افزودن توضیح به یک سلول، بر روی آن کلیک کنید و سپس یکی '
                'از کارهای زیر را انجام دهید:\n'
                '- بر روی سلول، راست\u200cکلیک کرده و گزینه\u200cی Insert '
                'Comment را انتخاب کنید.\n'
                '- در بخش Comments در برگه\u200cی Review بر روی New Comment '
                'کلیک کنید.\n'
                '- دکمه\u200cهای `Shift + F2` را بزنید.\n'
                'در کادر توضیح، در بخش زیرِ نام، متنی که برای توضیح '
                'می\u200cخواهید وارد کنید را بنویسید. وقتی نوشتن متن توضیح '
                'پایان یافت، دوباره بر روی آن سلول یا هر سلول دیگری کلیک '
                'کنید.\n'
                '\n'
                '### نمایش یا مخفی کردن توضیح\n'
                'برای نمایش یا مخفی کردن توضیح یک سلول، بر روی سلولی که نشانگر '
                'توضیح دارد، یکی از دو گزینه را انجام دهید:\n'
                '- بر روی سلول راست\u200cکلیک کرده و گزینه\u200cی Show/Hide '
                'Comment را انتخاب کنید.\n'
                '- در برگه\u200cی Review و در بخش Comments بر روی Show/Hide '
                'Comment کلیک کنید.\n'
                'برای نمایش همه\u200cی توضیح\u200cها در همه\u200cی '
                'صفحه\u200cهای یک فایل، در برگه\u200cی Review و در بخش '
                'Comments بر روی Show All Comments کلیک کنید. برای مخفی کردن '
                'همه\u200cی توضیح\u200cها نیز کافی است بار دیگر بر روی همین '
                'گزینه کلیک کنید.\n'
                '\n'
                'گزینه\u200cی Show All Comments، همه\u200cی توضیح\u200cهای '
                'صفحه گسترده را در فایل\u200cهای بازشده و همچنین همه\u200cی '
                'فایل\u200cهایی که وقتی گزینه فعال بوده است، باز یا ایجاد '
                'کرده\u200cاید را به\u200cحالت نمایش درمی\u200cآورد. شما '
                'نمی\u200cتوانید کاری کنید که در یک فایل، توضیح\u200cهای تنها '
                'یک صفحه گسترده، نمایش یابد. تنها راه\u200cحل این کار آن است '
                'که همه\u200cی توضیح\u200cها را به\u200cصورت '
                'تک\u200cبه\u200cتک به\u200cحالت نمایش درآورید.\n'
                '\n'
                '### جابجایی یا تغییر اندازه\u200cی توضیح\n'
                'اگر یکی از توضیح\u200cها بر روی توضیح\u200cهای دیگر قرار '
                'گرفته باشد می\u200cتوانید آن\u200cها را جابجا کنید. برای '
                'جابجایی یک توضیح باید آن را طوری تنظیم کرده باشید که بدون '
                'بردن ماوس روی سلول، قابل نمایش باشد. بنابراین توضیح را با '
                'استفاده از روشی که در بخش «نمایش یا مخفی کردن توضیح» گفتم '
                'نمایش دهید.\n'
                '\n'
                'نشانگر ماوس را به مرز کادر توضیح ببرید تا شکل نشانگر '
                'به\u200cصورت یک علامت بعلاوه دربیاید. سپس کلیک کنید تا کادر '
                'توضیح انتخاب شود. در این مرحله مشاهده می\u200cکنید که '
                'دستگیره\u200cهای اندازه\u200cبندی در کناره\u200cها و '
                'گوشه\u200cهای کادر، نمایش می\u200cیابند.\n'
                '\n'
                'با نگه\u200cداشتن نشانگر ماوس روی مرز کادر توضیح '
                'می\u200cتوانید بر روی آن کلیک کرده و آن را به موقعیت دیگری '
                'بکشید.\n'
                '\n'
                '### ویرایش یک توضیح\n'
                'ویرایش یک توضیح پس از ایجاد آن، کاری آسان است. برای ویرایش یک '
                'توضیح، بر روی سلول حاوی آن کلیک کنید و یکی از کارهای زیر را '
                'انجام دهید:\n'
                '- بر روی سلول راست\u200cکلیک کرده و گزینه\u200cی Edit Comment '
                'را انتخاب کنید.\n'
                '- در برگه\u200cی Review و در بخش Comments، گزینه\u200cی Edit '
                'Comment را انتخاب کنید.\n'
                '- دکمه\u200cی `Shift + F2` را بزنید.\n'
                'اگر سلول انتخابی توضیحی نداشته باشد، دکمه\u200cی Edit Comment '
                'به\u200cصورت New Comment نمایش می\u200cیابد.\n'
                '\n'
                'شما می\u200cتوانید توضیحِ درون کادر را اضافه، ویرایش یا حذف '
                'کنید. زمانی\u200cکه تغییرات مورد نیاز را انجام دادید، دوباره '
                'بر روی آن سلول یا هر سلول دیگر کلیک کنید.\n'
                '\n'
                '### حذف یک توضیح\n'
                'برای این\u200cکه یک توضیح را از سلولی حذف کنید، آن سلول را '
                'انتخاب کرده و یکی از گزینه\u200cهای زیر را اجرا کنید:\n'
                '- بر روی سلول راست\u200cکلیک کرده و گزینه\u200cی Delete '
                'Comment را انتخاب کنید.\n'
                '- در برگه\u200cی Review و در بخش Comments بر روی Delete کلیک '
                'کنید.\n'
                'زمانی\u200cکه یک توضیح حذف می\u200cشود، هیچ صفحه\u200cی '
                'تأییدی به نمایش درنمی\u200cآید، بنابراین هنگام حذف '
                'توضیح\u200cها باید هوشیار باشید.\n'
                '\n'
                '### قالب\u200cبندی یک توضیح\n'
                'متون توضیحات به\u200cطور پیش\u200cفرض با فونت Tahoma نمایش '
                'می\u200cیابند. شما نمی\u200cتوانید نوع و اندازه\u200cی فونت '
                'پیش\u200cفرض را تغییر دهید؛ اما می\u200cتوانید قالب\u200cبندی '
                'متنی که در بخش توضیحات وارد می\u200cکنید را عوض کنید.\n'
                '\n'
                'برای قالب\u200cبندی یک توضیح، ابتدا آن را به\u200cحالت قابل '
                'ویرایش دربیاورید. روند این کار در بخش «ویرایش یک توضیح» در '
                'بالا توضیح داده شده است. پس متنی که می\u200cخواهید '
                'قالب\u200cبندی کنید را هایلایت کنید، سپس بر روی متن انتخابی '
                'راست\u200cکلیک کرده و گزینه\u200cی Format Comment را انتخاب '
                'کنید.\n'
                'در صفحه\u200cی Format Comment می\u200cتوانید گزینه\u200cهای '
                'مختلفی را که می\u200cخواهید، برای قالب\u200cبندی متن توضیح، '
                'مورد استفاده قرار دهید. برای مثال برخی متن\u200cها را با '
                'استفاده از کادر Font Style و انتخاب color از فهرست بازشدنی '
                'می\u200cتوان به\u200cحالت درشت (Bold) و رنگ قرمز درآورد.\n'
                '\n'
                'زمانی\u200cکه نشانگر ماوس را برای نمایش توضیح، روی سلول ببرید '
                'یا با شرحی که در بخش «نمایش یا مخفی کردن توضیح»، توضیح دادم، '
                'آن را به\u200cحالت نمایشی درآوردید، می\u200cتوانید '
                'قالب\u200cبندی جدیدی که انتخاب کرده\u200cاید را ببینید.\n'
                '\n'
                'همچنین می\u200cتوانید از ابزارهای قالب\u200cبندی در '
                'برگه\u200cی Home برای قالب دادن به متن انتخابی در کادر توضیح '
                'استفاده کنید. اما نمی\u200cتوانید رنگ فونت یا رنگ '
                'زمینه\u200cی کادر را در برگه\u200cی Home تغییر دهید. برای این '
                'منظور باید اختصاصاً از صفحه\u200cی Format Comment استفاده '
                'کنید.\n'
                '\n'
                '### کپی کردن توضیح به سلول دیگر\n'
                'اگر بخواهید توضیح یکسانی را به چند سلول اضافه کنید، '
                'می\u200cتوانید آن توضیح را ابتدا در یک سلول قرار دهید و سپس '
                'آن را در سلول\u200cهای مورد نظر دیگر کپی کرده و بچسبانید. اما '
                'یک روش اختصاصی نیز برای این کار وجود دارد؛\n'
                'بر روی سلولی که حاوی توضیح است و می\u200cخواهید آن را کپی '
                'کنید کلیک کرده و `Ctrl + C` را بزنید. سپس بر روی سلولی که '
                'می\u200cخواهید توضیح کپی\u200cشده را بچسبانید، راست\u200cکلیک '
                'کرده و گزینه\u200cی Paste Special را انتخاب کنید.\n'
                'در صفحه\u200cی Paste Special بر روی Comments کلیک کرده و در '
                'بخش paste بر روی OK کلیک کنید.\n'
                'در این\u200cحالت تنها توضیح در مقصد چسبانده می\u200cشود و '
                'محتویات سلول، دست\u200cنخورده حفظ می\u200cشود.\n'
                '\n'
                '### حذف نشانگر توضیح از سلول\n'
                'اگر توضیحات زیادی داشته باشید، نشانگرهای توضیح (مثلث\u200cهای '
                'کوچک قرمز در گوشه\u200cی بالایی سلول) ممکن است باعث '
                'حواس\u200cپرتی شوند. به\u200cخصوص این مسئله در مواردی که '
                'می\u200cخواهید فایل را در اختیار کس دیگری قرار دهید، بیشتر '
                'اهمیت پیدا می\u200cکند.\n'
                '\n'
                'می\u200cتوان به\u200cسادگی، همه\u200cی نشانگرهای توضیحات را '
                'از سلول\u200cها حذف کرد. کافی است به مسیر File > Options '
                'بروید و در سمت چپ صفحه\u200cی Excel Options بر روی Advanced '
                'کلیک کنید.\n'
                'در سمت راست صفحه\u200cی Excel Options تا رسیدن به بخش Display '
                'اسکرول کنید. زیرِ بخش For cells with comments, show، '
                'گزینه\u200cی No comments or indicators را انتخاب کنید. وقتی '
                'این گزینه انتخاب شده باشد، بردن نشانگر ماوس روی سلولِ دارای '
                'توضیح، باعث نمایش توضیح نخواهد شد.\n'
                'زمانی\u200cکه هم توضیح و هم نشانگر آن مخفی شده\u200cاند، شما '
                'نمی\u200cتوانید از گزینه\u200cی Show/Hide Comment برای نمایش '
                'انفرادی توضیح یک سلول استفاده کنید. به\u200cجای آن '
                'می\u200cتوانید در برگه\u200cی Review و در بخش Comments بر روی '
                'گزینه\u200cی Show All Comments کلیک کنید تا همه\u200cی '
                'توضیح\u200cها نمایش یابند. این کار همچنین همه\u200cی '
                'نشانگرهای توضیح\u200cها را به نمایش درمی\u200cآورد.\n'
                '\n'
                'گزینه\u200cی Show All Comments به گزینه\u200cی For cells with '
                'comments, show اتصال یافته است؛ بنابراین فعال کردن Show All '
                'Comments باعث می\u200cشود که گزینه\u200cی For cells with '
                'comments, show به\u200cصورت Comments and indicators دربیاید.\n'
                'در این\u200cحالت باز ممکن است نشانگرهای توضیحات را نتوانید '
                'ببینید. اما رفتن به پنجره\u200cی یک برنامه\u200cی دیگر و سپس '
                'بازگشتن به پنجره\u200cی اکسل باعث می\u200cشود که نشانگرهای '
                'توضیحات به نمایش درآیند.\n'
                '\n'
                'زمانی\u200cکه گزینه\u200cی Show All Comments را انتخاب '
                'می\u200cکنید، اکسل به\u200cحالت پیش\u200cفرضِ نمایش نشانگرهای '
                'توضیحات و نمایش توضیحات درصورت رفتن ماوس روی آن\u200cها '
                'بازمی\u200cگردد. بدین ترتیب گزینه\u200cی For cells with '
                'comments, show به\u200cصورت Indicators only, and comments on '
                'hover درمی\u200cآید.\n'
                '\n'
                '### مرور همه\u200cی توضیح\u200cهای یک فایل\n'
                'برای این\u200cکه همه\u200cی توضیح\u200cهای یک صفحه گسترده را '
                'یک\u200cجا ببینید می\u200cتوانید ماوس را یک\u200cبه\u200cیک '
                'روی همه\u200cی سلول\u200cهای دارای توضیح ببرید، اما این کار '
                'زمان\u200cگیری است.\n'
                '\n'
                'یک روش سریع\u200cتر این است که در برگه\u200cی Review و در بخش '
                'Comments بر روی دکمه\u200cهای Next و Previous بزنید تا '
                'به\u200cترتیب به توضیح\u200cهای قبلی و بعدی هدایت شوید. این '
                'توضیح\u200cها هربار که بر روی یکی از دکمه\u200cها '
                'می\u200cزنید، یک\u200cبه\u200cیک نمایش می\u200cیابند.\n'
                '\n'
                '### پرینت یک صفحه گسترده با توضیحات\n'
                'بهتر است که توضیحات یک صفحه گسترده را به\u200cجای پرینت '
                'گرفتن، به\u200cصورت دیجیتالی مرور کنید. اما اگر به هر دلیل '
                'ترجیح می\u200cدهید توضیح\u200cها را روی یک کاغذ بخوانید، '
                'می\u200cتوانید صفحه گسترده\u200cی خود را همراه با '
                'توضیح\u200cها پرینت بگیرید.\n'
                '\n'
                'برای پرینت صفحه گسترده همراه با توضیح\u200cها، بر روی '
                'برگه\u200cی انتهای صفحه گسترده\u200cای که می\u200cخواهید '
                'پرینت بگیرید، کلیک کنید. سپس با استفاده از روش\u200cهایی که '
                'در بخش\u200cهای فوق توضیح دادم، همه\u200cی توضیح\u200cها یا '
                'توضیح\u200cهایی که می\u200cخواهید پرینت بگیرید را به نمایش '
                'درآورید. در این\u200cحالت با استفاده از راهنمایی\u200cهای بخش '
                '«جابجایی یا تغییر اندازه\u200cی توضیح» می\u200cتوانید '
                'توضیح\u200cها را درصورت لزوم جابجا کرده یا تغییر اندازه بدهید '
                'تا همه\u200cی موارد، خوانا باشند.\n'
                '\n'
                'درنهایت در برگه\u200cی Page Layout و در بخش Page Setup بر روی '
                'Page Setup کلیک کنید تا صفحه\u200cای باز شود؛\n'
                'در این صفحه بر روی برگه\u200cی Sheet کلیک کرده و سپس یکی از '
                'گزینه\u200cهای زیر را از فهرست بازشدنی Comments انتخاب کنید:\n'
                '- اگر می\u200cخواهید توضیح\u200cها همان جایی که قرار دارند '
                'پرینت شوند، گزینه\u200cی As displayed on sheet را انتخاب '
                'کنید. توجه داشته باشید که پرینت گرفتن توضیح\u200cها '
                'به\u200cصورتی\u200cکه روی صفحه\u200c، نمایش می\u200cیابند، '
                'می\u200cتواند باعث شود روی برخی سلول\u200cها پوشانده شود.\n'
                '- اگر نمی\u200cخواهید هیچ\u200cکدام از سلول\u200cها پوشانده '
                'شوند، گزینه\u200cی At end of sheet را انتخاب کنید؛ این کار، '
                'همه\u200cی توضیح\u200cها را در انتهای صفحه و با ارجاع به '
                'شماره\u200cی هر سلول چاپ می\u200cکند.\n'
                'زمانی\u200cکه آماده\u200cی پرینت صفحه گسترده همراه با توضیحات '
                'شدید، بر روی Print کلیک کنید؛\n'
                'بدین ترتیب صفحه\u200cی Print در برگه\u200cی File نمایش '
                'می\u200cیابد و پیش\u200cنمایشی از نحوه\u200cی پرینت صفحه '
                'گسترده همراه با توضیح\u200cها را می\u200cتوانید ببینید. در '
                'این صفحه، پرینتر خود را انتخاب کرده و صفحه گسترده را پرینت '
                'کنید.'}

### 🔴 Measuring RAM Usage After Dataset Loading

In [9]:
base_path = "parquet/"

files = [
    "Alphabet_NLP_Dataset.parquet",
    "Alphabet_Codex_Dataset.parquet",
    "Alphabet_Jurisprudence_Dataset.parquet",
    "Alphabet_Quran_Dataset.parquet",
    "Alphabet_Science_Dataset.parquet",
    "Alphabet_Technology_Dataset.parquet",
    "Alphabet_Philologia_Dataset.parquet"
]

process = psutil.Process(os.getpid())
ram_before = process.memory_info().rss  # bytes

datasets = [pd.read_parquet(base_path + file) for file in files]
dataset = pd.concat(datasets, ignore_index=True)

ram_after = process.memory_info().rss  # bytes

ram_used = ram_after - ram_before
print(f"🔹 RAM used for loading merged dataset: {ram_used / (1024**2):.2f} MB")

🔹 RAM used for loading merged dataset: 4.28 MB

In [10]:
train_full = list(dataset["target_text"])
print(f"🔹 Number of training samples: {len(train_full)}")

🔹 Number of training samples: 1032

In [15]:
tokenizer = Tokenizer.from_file("tokenizer/bpe-tokenizer_alphabet_nlp_dataset_10,000.json")
texts = []

for _, row in dataset.iterrows():
    texts.append(str(row["input_text"]).replace("\u200c", "<ZWNJ>"))
    texts.append(str(row["target_text"]).replace("\u200c", "<ZWNJ>"))

total_tokens = sum(
    len(tokenizer.encode(text).ids)
    for text in texts
)

print(f"🔢 Total tokens: {total_tokens:,}")

🔢 Total tokens: 467,892

### 🔴 Tokenization

In [10]:
base_path = "parquet/"

files = [
    "Alphabet_NLP_Dataset.parquet",
    "Alphabet_Codex_Dataset.parquet",
    "Alphabet_Jurisprudence_Dataset.parquet",
    "Alphabet_Quran_Dataset.parquet",
    "Alphabet_Science_Dataset.parquet",
    "Alphabet_Technology_Dataset.parquet",
    "Alphabet_Philologia_Dataset.parquet"
]

datasets = [pd.read_parquet(base_path + file) for file in files]
dataset = pd.concat(datasets, ignore_index=True)

texts = []

for _, row in dataset.iterrows():
    texts.append(str(row["input_text"]).replace("\u200c", "<ZWNJ>"))
    texts.append(str(row["target_text"]).replace("\u200c", "<ZWNJ>"))

tokenizer = Tokenizer(models.BPE(unk_token="|<unk>|"))

tokenizer.pre_tokenizer = pre_tokenizers.ByteLevel(
    add_prefix_space=True
)

trainer = trainers.BpeTrainer(
    vocab_size=10_000,
    special_tokens=["|<unk>|", "<|endoftext|>"],
    min_frequency=2,
)

tokenizer.train_from_iterator(texts, trainer)

tokenizer.decoder = decoders.ByteLevel(
    add_prefix_space=True,
    clean_up_tokenization_spaces=False
)

total_tokens = 0

for text in texts:
    total_tokens += len(tokenizer.encode(text).ids)

json_out = "tokenizer/bpe-tokenizer_alphabet_nlp_dataset_10,000.json"

os.makedirs("tokenizer", exist_ok=True)
tokenizer.save(json_out)

print("🎉 Tokenizer training complete!")
print(f"🔢 tokens: {total_tokens:,}")
print(f"🔹 Vocabulary size: {tokenizer.get_vocab_size():,} tokens")

🎉 Tokenizer training complete!
🔢 tokens: 465,694
🔹 Vocabulary size: 10,000 tokens

### 🔴 Measuring RAM Usage After Tokenization

In [14]:
tokenizer = Tokenizer.from_file("tokenizer/bpe-tokenizer_alphabet_nlp_dataset_10,000.json")

# Calculate RAM usage after loading
process = psutil.Process(os.getpid())
mem_info = process.memory_info()
ram_mb = mem_info.rss / (1024 ** 2)

print(f"💾 RAM Usage after loading tokenizer: {ram_mb:.2f} MB")

💾 RAM Usage after loading tokenizer: 181.79 MB

### 🔴 Tokenizer Test

In [12]:
# Load the trained tokenizer
tokenizer = Tokenizer.from_file("tokenizer/bpe-tokenizer_alphabet_nlp_dataset_10,000.json")

# Sample text containing special tokens
sample_text = "###عنوان\n\nاین\nیک متن **مهم** با نیم‌فاصله است."

# Encode the sample text
encoded_output = tokenizer.encode(sample_text)

# Print the tokens and their decoded representation
print(f"Original text:\n{sample_text}")
print(f"Encoded tokens: {encoded_output.tokens}")
print(f"Decoded text:\n{tokenizer.decode(encoded_output.ids)}")

Original text:
###عنوان

این
یک متن **مهم** با نیم‌فاصله است.
Encoded tokens: ['Ġ###', 'Ø¹ÙĨÙĪØ§ÙĨ', 'Ċ', 'Ċ', 'Ø§ÛĮÙĨ', 'Ċ', 'ÛĮÚ©', 'ĠÙħØªÙĨ', 'Ġ**', 'ÙħÙĩÙħ', '**', 'ĠØ¨Ø§', 'ĠÙĨ', 'ÛĮÙħ', 'âĢ', 'Į', 'Ùģ', 'Ø§ØµÙĦÙĩ', 'ĠØ§Ø³Øª', '.']
Decoded text:
 ###عنوان

این
یک متن **مهم** با نیم‌فاصله است.